services:
  api:
    image: localhost:5000/retirement-api:latest
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT:-5434}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - 8185:8000
    restart: unless-stopped
  frontend:
    image: localhost:5000/retirement-frontend:latest
    ports:
      - 8186:80
    restart: unless-stopped
networks: {}
