import csv
import json
import logging
from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional

import numpy as np

from models.config import BaseAssetConfig

FMT = "%Y-%m-%d"
DAYS_IN_YEAR = 365.25
MONTHS_IN_YEAR = 12

_BASE_CONFIG_FIELDS = frozenset(
    ("name", "description", "type", "start_date", "end_date", "tax_class")
)


@dataclass
class AssetState:
    """Mutable simulation state for one asset, separated from static config."""

    value: float = 0.0
    debt: float = 0.0
    income: float = 0.0
    expenses: float = 0.0
    growth_rate: float = 0.0
    growth_rate_volatility: float = 0.0
    expense_rate: float = 0.0


class Asset:

    def __init__(self, filename: str) -> None:
        """Initialize the asset object by loading its properties from a JSON file.

        The initializer reads the provided JSON file, parses its contents, and
        updates the object's dictionary with the values. After loading, a setup
        method ensures additional processing is completed.

        Required fields in the JSON file or after _setup():
         - name
         - description
         - type  # e.g., RE, Equity, Salary
         - start_date
         - end_date
         - tax_class

        Parameters:
            filename: The path to the JSON file that contains the asset data.
        """
        logging.debug(f" *** Initializing asset from {filename} ***")
        with open(filename, "r") as reader:
            data = json.load(reader)
        self.__dict__.update(data)

        # State must be created after __dict__.update so JSON keys cannot
        # accidentally overwrite the _state attribute.
        self._state = AssetState()

        # Build typed config from base fields present in the JSON.
        base_fields = {k: data[k] for k in _BASE_CONFIG_FIELDS if k in data}
        self.config: BaseAssetConfig = BaseAssetConfig(**base_fields)

        self.initialize_asset_metrics()  # Ensure all financial attributes are initialized
        self._initialize_derived_metrics_functions()
        for key in ["start_date", "end_date", "retirement_date"]:
            # Attempt to parse date strings into datetime.date objects
            if key in self.__dict__:
                try:
                    self.__dict__[key] = datetime.strptime(self.__dict__[key], FMT).date()
                    # Bug fix: was logging undefined `e` in the success path
                    logging.info(
                        f"Parsed date for {key} in {filename}: {self.__dict__[key]}"
                    )
                except (ValueError, TypeError) as e:
                    logging.info(f"Did not parse date for {key} in {filename}: {e}")
        self.setup_run = False
        logging.debug(f"Initial values of required values: {str(self)}")

    @classmethod
    def from_file(cls, filename: str) -> "Asset":
        """Factory method — alias for the filename constructor.

        Args:
            filename: Path to the JSON asset configuration file.

        Returns:
            A fully initialised Asset (or subclass) instance.
        """
        return cls(filename)

    # ------------------------------------------------------------------
    # State properties — delegate read/write to self._state so callers
    # see a stable interface whether they go through the property or not.
    # ------------------------------------------------------------------

    @property
    def value(self) -> float:
        """Current asset value."""
        return self._state.value

    @value.setter
    def value(self, v: float) -> None:
        self._state.value = float(v)

    @property
    def debt(self) -> float:
        """Current outstanding debt against the asset."""
        return self._state.debt

    @debt.setter
    def debt(self, v: float) -> None:
        self._state.debt = float(v)

    @property
    def income(self) -> float:
        """Monthly income generated by the asset this period."""
        return self._state.income

    @income.setter
    def income(self, v: float) -> None:
        self._state.income = float(v)

    @property
    def expenses(self) -> float:
        """Monthly fixed expenses for this asset this period."""
        return self._state.expenses

    @expenses.setter
    def expenses(self, v: float) -> None:
        self._state.expenses = float(v)

    @property
    def growth_rate(self) -> float:
        """Monthly appreciation rate for this period."""
        return self._state.growth_rate

    @growth_rate.setter
    def growth_rate(self, v: float) -> None:
        self._state.growth_rate = float(v)

    @property
    def growth_rate_volatility(self) -> float:
        """Standard deviation of the monthly growth rate."""
        return self._state.growth_rate_volatility

    @growth_rate_volatility.setter
    def growth_rate_volatility(self, v: float) -> None:
        self._state.growth_rate_volatility = float(v)

    @property
    def expense_rate(self) -> float:
        """Fractional expense rate applied to asset value each period."""
        return self._state.expense_rate

    @expense_rate.setter
    def expense_rate(self, v: float) -> None:
        self._state.expense_rate = float(v)

    # ------------------------------------------------------------------

    def _initialize_derived_metrics_functions(self) -> None:
        self.metrics_functions = {
            "appreciation": self._asset_appreciation,
            "cash_flow": self.cash_flow,
            "operating_expense": self.operating_expense,
            "taxable_income": self.taxable_income,
        }

    def initialize_asset_metrics(self) -> None:
        """Reset all financial state attributes to zero.

        Used to clear state when the asset is outside its active date range.
        """
        self.value = 0.0
        self.debt = 0.0
        self.income = 0.0
        self.expenses = 0.0
        self.growth_rate = 0.0
        self.growth_rate_volatility = 0.0
        self.expense_rate = 0.0

    def _setup(self) -> None:
        """Hook for subclass-specific first-period initialisation."""
        pass

    def pre_calculate(self, start_date: object) -> None:
        """Hook called once after scenario dates are resolved, before simulation runs.

        Subclasses override this to derive initial state from external data or
        schedules (e.g. computing a mortgage balance from an amortization table).
        The base implementation is a no-op so existing assets are unaffected.

        Args:
            start_date: The simulation start date (already resolved from placeholders).
        """
        pass

    def update_value_with_investment(self, incremental_investment: float) -> float:
        """Add an investment amount to the asset value.

        Parameters:
            incremental_investment: The amount to invest (may be negative for withdrawal).

        Returns:
            The actual amount invested (may differ if the asset would go negative).
        """
        if self.value + incremental_investment < 0:
            incremental_investment = -self.value
            self.value = 0.0
            logging.warning(
                f"Investment amount is negative and exceeds current value of {self.name}"
            )
        else:
            self.value += incremental_investment
        logging.info(
            f"Invested ${incremental_investment:,.2f} into {self.name}. New value: ${self.value:,.2f}"
        )
        return incremental_investment

    def _period_update_finalize_metrics(
        self, period: int, period_date: Optional[object] = None
    ) -> None:
        """Subclass hook called once per period before metric functions run."""
        pass

    def period_update(self, period: int, period_date: Optional[object] = None) -> tuple:
        """Update the asset for one simulation period.

        Parameters:
            period: Zero-based period index.
            period_date: The calendar date for this period.

        Returns:
            (period, period_date, derived_metrics_dict)
        """
        derived_metrics = {k: 0.0 for k in self.metrics_functions}
        if self.start_date is not None and self.end_date is not None:
            if period_date < self.start_date:
                logging.info(
                    f"Asset {self.name} not applicable for period {period} on date {period_date}"
                )
            elif self.start_date <= period_date < self.end_date:
                if not self.setup_run:
                    self._setup()
                    self.setup_run = True
                    logging.debug(f"Run asset setup: {str(self)}")
                logging.info(
                    f"Updating asset {self.name} for period {period} on date {period_date}"
                )
                self._period_update_finalize_metrics(period, period_date)
                for k, f in self.metrics_functions.items():
                    derived_metrics[k] = f()
                    logging.debug(
                        f"Derived metrics for {self.name} at period {period}: {k} = {derived_metrics[k]:.2f}"
                    )
            else:
                logging.info(
                    f"Asset {self.name} not applicable for period {period} on date {period_date}, resetting values."
                )
                self.initialize_asset_metrics()
        else:
            logging.error(
                f"Invalid period_date: {period_date} or asset dates: {self.start_date}, {self.end_date}"
            )
        return period, period_date, derived_metrics

    def period_snapshot(
        self, period: int, period_date: Optional[object] = None, addl: dict = {}
    ) -> list:
        """Return a list snapshot of the asset state for this period.

        Arguments:
            period: The period index.
            period_date: The calendar date for this period.
            addl: Optional additional key/value pairs to append.

        Returns:
            List of [period, date, name, description, value, debt, income, expenses, ...]
        """
        self.snapshot_header = [
            "Period",
            "Date",
            "Name",
            "Description",
            "Value",
            "Debt",
            "Income",
            "Expenses",
        ]
        res = [
            period,
            period_date,
            self.name,
            self.description,
            self.value,
            self.debt,
            self.income,
            self.expenses,
        ]
        if len(addl) > 0:
            for key, value in addl.items():
                res.append(value)
                self.snapshot_header.append(key)
        return res

    def _asset_appreciation(self) -> float:
        """Apply appreciation to the asset value and return the increment.

        Bug fix: the original code had a misspelled ``hasattr`` check
        (``growth_rate_volatiliy``) that was always False, causing
        ``np.random.normal`` to be called even when volatility is zero.
        The fix: check ``self.growth_rate_volatility == 0.0`` directly.

        Returns:
            The appreciation amount added to self.value.
        """
        # Bug fix: was `hasattr(self, "growth_rate_volatiliy")` (misspelled),
        # making the condition always False and always sampling from normal.
        if self.growth_rate_volatility == 0.0:
            rate = self.growth_rate
        else:
            rate = np.random.normal(self.growth_rate, self.growth_rate_volatility)
        inc = self.value * rate
        self.value += inc
        logging.info(
            f"Appreciation for {self.name} at rate {rate:.4f} is ${inc:,.2f}, new value is ${self.value:,.2f}"
        )
        return inc

    def operating_expense(self) -> float:
        """Return total operating expense = value * expense_rate + fixed expenses."""
        return self.value * self.expense_rate + self.expenses

    def cash_flow(self) -> float:
        """Return net cash flow = income - operating_expense."""
        return self.income - self.operating_expense()

    def taxable_income(self) -> float:
        """Return monthly taxable income for this asset."""
        return self.income

    def set_scenario_dates(self, date_dict: dict) -> None:
        """Update start/end dates from a scenario-level date mapping.

        Parameters:
            date_dict: Maps placeholder strings (e.g. "retirement") to actual dates.
        """
        for key, value in date_dict.items():
            if self.start_date == key:
                if isinstance(value, str):
                    self.start_date = datetime.strptime(value, FMT).date()
                else:
                    self.start_date = value
            elif self.end_date == key:
                if isinstance(value, str):
                    self.end_date = datetime.strptime(value, FMT).date()
                else:
                    self.end_date = value
            elif hasattr(self, "retirement_age") and self.retirement_age == key:
                self.retirement_age = int(value)
            elif hasattr(self, "retirement_date") and self.retirement_date == key:
                if isinstance(value, str):
                    self.retirement_date = datetime.strptime(value, FMT).date()
                else:
                    self.retirement_date = value

    def __repr__(self) -> str:
        return (
            f"{self.name}: ${self.value:,.2f}, ${self.debt:,.2f}, ${self.income:,.2f}, "
            f"${self.expenses:,.2f} ,{self.growth_rate:,.2f}, {self.expense_rate:,.2f}"
        )


class REAsset(Asset):
    """Real estate asset with mortgage, rental income, and property expenses."""

    def _setup(self) -> None:
        """Initialise rates and balances from the JSON configuration."""
        self.value = self.initial_value
        self.debt = self.initial_debt
        self.growth_rate = self.appreciation_rate / MONTHS_IN_YEAR
        # appreciation_rate_volatility is optional; 0 = deterministic (default)
        self.growth_rate_volatility = getattr(self, "appreciation_rate_volatility", 0.0)
        self.expense_rate = self.property_tax_rate / MONTHS_IN_YEAR
        self.income_based_expenses_rate = self.management_fee_rate + self.rental_expense_rate
        self.income = self.monthly_rental_income
        self.monthly_interest_rate = self.interest_rate / MONTHS_IN_YEAR
        # extra_principal_payment is optional; 0 = no extra paydown (default)
        self._extra_principal = getattr(self, "extra_principal_payment", 0.0)

    def _period_update_finalize_metrics(
        self, period: int, period_date: Optional[object] = None
    ) -> None:
        """Advance the mortgage one period and update expense components."""
        interest = self.debt * self.monthly_interest_rate
        regular_payment = min(self.payment, self.debt + interest)
        self.principle_payment = regular_payment - interest
        self.debt -= self.principle_payment

        # Extra principal paydown: applied only while debt remains, added to cash outflow.
        extra = min(self._extra_principal, self.debt)
        self.debt -= extra

        self.expenses = self.insurance_cost / MONTHS_IN_YEAR
        self.expenses += self.income_based_expenses_rate * self.income
        self.expenses += regular_payment + extra
        logging.info(
            f"mort_status, {self.name}, {period}, {period_date}, "
            f"payment={regular_payment:.2f}, interest={interest:.2f}, "
            f"principal={self.principle_payment:.2f}, extra={extra:.2f}, balance={self.debt:.2f}"
        )

    def pre_calculate(self, start_date: object) -> None:
        """Compute the mortgage balance at start_date from the amortization schedule.

        Reads two optional config fields:
          - loan_origination_date: date the mortgage was originated (YYYY-MM-DD)
          - original_loan_amount:  original principal at origination

        If either field is absent or None, falls back to the manually-specified
        initial_debt value — existing configs require no changes.

        The closed-form amortization balance formula used is:
            B(n) = L*(1+r)^n - PMT*((1+r)^n - 1)/r
        where n = months elapsed since origination, L = original amount,
        r = monthly interest rate, PMT = regular monthly payment.

        Args:
            start_date: The simulation start date.
        """
        orig_date_raw = getattr(self, "loan_origination_date", None)
        orig_amount = getattr(self, "original_loan_amount", None)

        if orig_date_raw is None or orig_amount is None:
            logging.info(
                f"{self.name}: no origination data; using initial_debt={self.initial_debt:,.2f}"
            )
            return

        if isinstance(orig_date_raw, str):
            orig_date = datetime.strptime(orig_date_raw, FMT).date()
        else:
            orig_date = orig_date_raw

        if start_date <= orig_date:
            # Simulation starts at or before origination — use original amount.
            self.initial_debt = float(orig_amount)
            logging.info(f"{self.name}: start_date ≤ origination; initial_debt set to original loan amount")
            return

        months_elapsed = (
            (start_date.year - orig_date.year) * 12
            + (start_date.month - orig_date.month)
        )
        r = self.interest_rate / MONTHS_IN_YEAR
        L = float(orig_amount)
        pmt = self.payment

        if r == 0.0:
            balance = max(0.0, L - pmt * months_elapsed)
        else:
            factor = (1.0 + r) ** months_elapsed
            balance = L * factor - pmt * (factor - 1.0) / r

        self.initial_debt = max(0.0, balance)
        logging.info(
            f"{self.name}: pre-calculated mortgage balance at {start_date} "
            f"= ${self.initial_debt:,.2f} ({months_elapsed} months from origination)"
        )


class Equity(Asset):
    """Equity asset with dividend income and optional stochastic appreciation.

    Attributes:
        growth_rate: Monthly appreciation rate.
        expense_rate: Monthly expense rate.
        dividend_rate: Monthly dividend yield.
    """

    def _setup(self) -> None:
        """Initialise monthly rates from annual config values."""
        self.sampled_flag = False
        self.growth_rate = self.appreciation_rate / MONTHS_IN_YEAR
        self.growth_rate_volatility = self.appreciation_rate_volatility
        if (
            "sampled_monthly_sp500_returns" in self.__dict__
            and self.sampled_monthly_sp500_returns is not None
        ):
            with open(self.sampled_monthly_sp500_returns, "r") as f:
                self.sampled_growth_rate: list[float] = []
                rdr = csv.reader(f)
                for row in rdr:
                    try:
                        self.sampled_growth_rate.append(float(row[0]))
                    except ValueError as e:
                        logging.error(f"Error parsing sampled monthly returns: {e}")
                        continue
            if len(self.sampled_growth_rate) > 0:
                self.sampled_flag = True
                self.growth_rate_volatility = 0.0
        self.expense_rate = self.initial_expense_rate / MONTHS_IN_YEAR
        self.dividend_rate /= MONTHS_IN_YEAR
        self.value = self.initial_value
        self.capital_gains = 0.0

    def _period_update_finalize_metrics(
        self, period: int, period_date: Optional[object] = None
    ) -> None:
        """Update income from dividends; optionally sample historical returns."""
        self.income = self.value * self.dividend_rate
        if self.sampled_flag:
            self.growth_rate = self.sampled_growth_rate[
                np.random.randint(0, len(self.sampled_growth_rate))
            ]
            self.growth_rate_volatility = 0.0

    def withdraw_income(self, amount: float) -> None:
        """Reduce asset value by a withdrawal amount.

        Parameters:
            amount: The amount to withdraw.
        """
        self.value -= amount
        self.capital_gains = (
            self.initial_value * self.growth_rate ** period  # type: ignore[name-defined]
        )
        logging.info(
            f"Withdrew ${amount:,.2f} from {self.name} value = {self.value:,.2f}, "
            f"capital gains = {self.capital_gains:,.2}"
        )

    def taxable_income(self) -> float:
        """Return dividends minus expenses plus realised capital gains."""
        return self.income - self.expenses + self.capital_gains


class SalaryIncome(Asset):
    """Employment or benefit income that grows with a COLA rate."""

    def _setup(self) -> None:
        """Initialise income from salary or age-based benefit table."""
        self.growth_rate = self.cola / MONTHS_IN_YEAR
        if "retirement_age_based_benefit" in self.__dict__:
            self.salary = self.retirement_age_based_benefit[str(self.retirement_age)]
            self.income = self.salary
            logging.info(
                f"Using benefit for retirement age {self.retirement_age}: {self.salary}"
            )
        else:
            logging.info(f"No age based benefit found, using salary: {self.salary}")
            self.income = self.salary / MONTHS_IN_YEAR

    def _period_update_finalize_metrics(
        self, period: int, period_date: Optional[object] = None
    ) -> None:
        """Apply COLA growth to monthly income."""
        self.income *= 1.0 + self.growth_rate
